ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "User" FOR ALL USING (false);

ALTER TABLE "AttorneyProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttorneyProfile" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "AttorneyProfile" FOR ALL USING (false);

ALTER TABLE "Availability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Availability" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "Availability" FOR ALL USING (false);

ALTER TABLE "BlockedDate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlockedDate" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "BlockedDate" FOR ALL USING (false);

ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "Booking" FOR ALL USING (false);

ALTER TABLE "Review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "Review" FOR ALL USING (false);

ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" FORCE ROW LEVEL SECURITY;
CREATE POLICY "deny_all" ON "_prisma_migrations" FOR ALL USING (false);
